export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const GET_CATEGORY = "GET_CATEGORY";
export const CLEAR_CATEGORY = "CLEAR_CATEGORY";
export const ERROR_CATEGORY = "CLEAR_CATEGORY";
export const SET_CURRENT = "SET_CURRENT";
